"""empty message

Revision ID: 311c81986caf
Revises: 
Create Date: 2018-06-20 14:36:38.799493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '311c81986caf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('research_id', sa.Integer(), nullable=True),
    sa.Column('projtitle_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.String(length=700), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['projtitle_id'], ['projtitles.id'], ),
    sa.ForeignKeyConstraint(['research_id'], ['researchs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('research_id', sa.Integer(), nullable=True),
    sa.Column('doc_name', sa.String(), nullable=True),
    sa.Column('doc_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['research_id'], ['researchs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('imgs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('research_id', sa.Integer(), nullable=True),
    sa.Column('stock_id', sa.Integer(), nullable=True),
    sa.Column('img_name', sa.String(), nullable=True),
    sa.Column('img_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['research_id'], ['researchs.id'], ),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('research_id', sa.Integer(), nullable=True),
    sa.Column('vid_name', sa.String(), nullable=True),
    sa.Column('vid_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['research_id'], ['researchs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('disccoms')
    op.drop_column('projects', 'image1_filename')
    op.drop_column('projects', 'image2_filename')
    op.drop_column('projects', 'image1_url')
    op.drop_column('projects', 'image3_url')
    op.drop_column('projects', 'video2_name')
    op.drop_column('projects', 'image2_url')
    op.drop_column('projects', 'image3_filename')
    op.drop_column('projects', 'video1_name')
    op.drop_column('projects', 'video2_url')
    op.drop_column('projects', 'video1_url')
    op.drop_column('researchs', 'file_url')
    op.drop_column('researchs', 'file_name')
    op.drop_column('stocks', 'image_url')
    op.drop_column('stocks', 'image_filename')
    op.add_column('votes', sa.Column('research_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'votes', 'researchs', ['research_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'votes', type_='foreignkey')
    op.drop_column('votes', 'research_id')
    op.add_column('stocks', sa.Column('image_filename', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('stocks', sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('researchs', sa.Column('file_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('researchs', sa.Column('file_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('video1_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('video2_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('video1_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('image3_filename', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('image2_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('video2_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('image3_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('image1_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('image2_filename', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('image1_filename', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_table('disccoms',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('projdisc_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('comment', sa.VARCHAR(length=300), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='disccoms_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='disccoms_pkey')
    )
    op.drop_table('videos')
    op.drop_table('imgs')
    op.drop_table('documents')
    op.drop_table('comments')
    # ### end Alembic commands ###
