"""empty message

Revision ID: d614d0a136ea
Revises: 311c81986caf
Create Date: 2018-06-22 05:53:33.968034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd614d0a136ea'
down_revision = '311c81986caf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('img_name', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('img_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'img_url')
    op.drop_column('projects', 'img_name')
    # ### end Alembic commands ###
